# Generated by Django 4.1.4 on 2022-12-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartProduct',
            new_name='CartProd',
        ),
    ]
