# Generated by Django 4.1.4 on 2023-05-17 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0002_alter_testmodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='имя категории')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='фото категории')),
            ],
        ),
        migrations.AddField(
            model_name='testmodel',
            name='product_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shopadmin.category', verbose_name='Имя категории'),
            preserve_default=False,
        ),
    ]
