# Generated by Django 4.1.4 on 2023-05-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0003_category_testmodel_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
