# Generated by Django 4.1.4 on 2023-05-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0004_alter_testmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='testmodel', verbose_name='фото товара'),
        ),
    ]
